### ISSUE TITLE
Inventory file format for OCP 4 installation should be provided

### ISSUE THREAD

**Issue by honghuac** [RedHatWorkshops/dayinthelife-streaming#10]
The sole existing [inventory file](https://github.com/RedHatWorkshops/dayinthelife-streaming/blob/master/support/install/ansible/inventory/inventory.example) has OCP 3 cluster as a target environment.

Since the [installation instructions](https://github.com/RedHatWorkshops/dayinthelife-streaming/blame/master/docs/install.md#L19) state that OCP 4 should be used, an inventory file meant for an OCP 4 environment should be provided.

**Comment by hguerrero** [comment]
Update the install process to work on OCP 4.2 and removed non necessary configs on the inventory file.

**Comment by hguerrero** [comment]
fixed with https://github.com/RedHatWorkshops/dayinthelife-streaming/commit/d27920ed0f36d79d1360ede98f29bad6a8142db2
