### ISSUE TITLE
Lab 2 - authorization issue with connector webpage

### ISSUE THREAD

**Issue by honghuac** [RedHatWorkshops/dayinthelife-streaming#11]
[This link](https://developers.redhat.com/topics/event-driven/connectors/) on the [lab 2 walkthrough](https://github.com/RedHatWorkshops/dayinthelife-streaming/blob/master/docs/labs/02-Change-Data-Capture/walkthrough.adoc) results in an authorization issue.

**Comment by hguerrero** [comment]
Article was published, should work now.
