### ISSUE TITLE
Solution Patterns URL

### ISSUE THREAD

**Issue by hguerrero** [RedHatWorkshops/dayinthelife-streaming#19]
Add a way to retrieve the solution patterns URL either from Ansible playbook finish or email.

**Comment by hodrigohamalho** [comment]
I think it's already done https://github.com/RedHatWorkshops/dayinthelife-streaming/blob/master/support/install/ansible/playbooks/openshift/install.yaml#L71

**Comment by hguerrero** [comment]
you are right @hodrigohamalho closed by https://github.com/RedHatWorkshops/dayinthelife-streaming/commit/6b47560a2d58eb6485b713f2688a20603399544c
