### ISSUE TITLE
Session Key timeout when installing more then 15 users for Che

### ISSUE THREAD

**Issue by weimeilin79** [RedHatWorkshops/dayinthelife-streaming#21]
Need to grab session key every time instead of using it for just once. or login again if 401

**Comment by hodrigohamalho** [comment]
I was able to work around this item changing the token timeouts on the master realm.
But need to work to put it on the playbook.

**Comment by hguerrero** [comment]
working on a solution to extend the token lifespan and reuse it for 1hr instead of the default time < 30 mins.

**Comment by hguerrero** [comment]
addressed by #31
