### ISSUE TITLE
Wrong description of Lab 1 - Event Driven Architecture

### ISSUE THREAD

**Issue by hodrigohamalho** [RedHatWorkshops/dayinthelife-streaming#28]
<img width="1187" alt="Wrong description of Lab 1" src="https://user-images.githubusercontent.com/252998/82577925-1040bd80-9b62-11ea-8e1c-a607e61bda94.png">

**Comment by hguerrero** [comment]
should be fixed with https://github.com/RedHatWorkshops/dayinthelife-streaming/commit/07f0e22af7d3b8626a3213b450b2e17324bd69ac
