### ISSUE TITLE
A che worspace being created for every ansible execution

### ISSUE THREAD

**Issue by hodrigohamalho** [RedHatWorkshops/dayinthelife-streaming#29]
It looks like that a Che workspace is created for every ansible execution. 

Sometimes the playbook fails and it's necessary to run it again for conclude the workshop install.

![Che workspaces](https://user-images.githubusercontent.com/252998/82685982-747b8400-9c2b-11ea-9d43-808b9ebf8cb4.png)

**Comment by weimeilin79** [comment]
Fixed
