### ISSUE TITLE
Make all labs independent

### ISSUE THREAD

**Issue by hodrigohamalho** [RedHatWorkshops/dayinthelife-streaming#36]
Consider that each lab can be delivered individually without any dependency on previous labs.

**Comment by weimeilin79** [comment]
@hguerrero  Lab3 and Lab4 are ready in module-split branch with JUST instruction updates.

**Comment by hguerrero** [comment]
currently working on `module-split` branch

**Comment by hguerrero** [comment]
closed by https://github.com/RedHatWorkshops/dayinthelife-streaming/pull/63/
