### ISSUE TITLE
Module 2 - Validate KafkaTopics were created - screenshot & text are off

### ISSUE THREAD

**Issue by edeandrea** [RedHatWorkshops/dayinthelife-streaming#50]
Sections 2.3 step 2 & 4.2 step 1 - Validate that the **KafkaTopics** were created

The **Advanced** menu isn't there - instead the menu is labelled **More**. The UI has been updated (newer OpenShift version).

![Screen Shot 2020-08-03 at 12 34 41 PM](https://user-images.githubusercontent.com/363447/89205434-bc9d1800-d585-11ea-977b-e98020076b85.png)

**Comment by hguerrero** [comment]
closed by https://github.com/RedHatWorkshops/dayinthelife-streaming/pull/63/
