### ISSUE TITLE
AMQ Online AddressSpacePlans and AuthenticationService templates are not created during install

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-streaming#6]
The following part of the ansible install script is failing to during install:

https://github.com/RedHatWorkshops/dayinthelife-streaming/blob/1ef1f82869552a1308d13506f2f17e9004904b01/support/install/ansible/playbooks/openshift/roles/provision_online/tasks/main.yaml#L56

Both AddressSpacePlan and AuthenticationService are unpopulated in the GUI dropdown

**Comment by hguerrero** [comment]
@sigreen can you check if you can access the link from your browser / curl command in the machine your are installing? Or do you have the error trace?

**Comment by sigreen** [comment]
@hguerrero I can access the link from my browser.  The issue is happening intermittently.  I'll see if I can get the error trace

**Comment by sigreen** [comment]
Here is the script output @hguerrero:

```TASK [provision_online : Evaluate workshop-operators namespace if not exists] *********************************************************************************************************
ok: [localhost]

TASK [provision_online : Evaluate Operator Group] *************************************************************************************************************************************
ok: [localhost]

TASK [provision_online : Evaluate Online CatalogSourceConfig] *************************************************************************************************************************
changed: [localhost]

TASK [provision_online : Evaluate Online Subscription] ********************************************************************************************************************************
changed: [localhost]

TASK [provision_online : Wait for Online operator to install] *************************************************************************************************************************
FAILED - RETRYING: Wait for Online operator to install (10 retries left).
FAILED - RETRYING: Wait for Online operator to install (9 retries left).
FAILED - RETRYING: Wait for Online operator to install (8 retries left).
FAILED - RETRYING: Wait for Online operator to install (7 retries left).
ok: [localhost]

TASK [provision_online : Add the Security Constraint Context] *************************************************************************************************************************
ok: [localhost]

TASK [provision_online : Set temp dir] ************************************************************************************************************************************************
ok: [localhost]

TASK [provision_online : Ensure example directory exists] *****************************************************************************************************************************
ok: [localhost]

TASK [provision_online : Download example files] **************************************************************************************************************************************
skipping: [localhost]

TASK [provision_online : Create Online Plan Examples] *********************************************************************************************************************************
```

Maybe because the /tmp directory already contains the address plans, it skips the task maybe?  Maybe we should consider removing the directory first if it already exists.

**Comment by sigreen** [comment]
I manually removed the `/tmp/amq-online` directory and re-ran the install script:

```
TASK [provision_online : Create Online Plan Examples] *********************************************************************************************************************************
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressSpacePlan-standard-small.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-StandardInfraConfig-default.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-medium-multicast.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-small-topic.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-large-topic.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-large-anycast.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-small-subscription.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-xlarge-topic.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-small-multicast.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressSpacePlan-standard-unlimited.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-large-subscription.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-small-anycast.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-medium-queue.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-brokered-queue.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-medium-anycast.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-StandardInfraConfig-default-minimal.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressSpacePlan-standard-unlimited-with-mqtt.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-brokered-topic.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-medium-topic.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressSpacePlan-standard-medium.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressSpacePlan-brokered-single-broker.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-large-queue.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-small-queue.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-large-multicast.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-BrokeredInfraConfig-default.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-medium-subscription.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-StandardInfraConfig-default-with-mqtt.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-plans/020-AddressPlan-standard-xlarge-queue.yaml)
changed: [localhost] => (item=/tmp/amq-online/install/components/example-authservices/standard-authservice.yaml)
```

The resolution is to include a step in the uninstall script to delete the /tmp/amq-online directory

**Comment by hguerrero** [comment]
> Here is the script output @hguerrero:
> 
> ```
> ok: [localhost]
> 
> TASK [provision_online : Evaluate Operator Group] *************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [provision_online : Evaluate Online CatalogSourceConfig] *************************************************************************************************************************
> changed: [localhost]
> 
> TASK [provision_online : Evaluate Online Subscription] ********************************************************************************************************************************
> changed: [localhost]
> 
> TASK [provision_online : Wait for Online operator to install] *************************************************************************************************************************
> FAILED - RETRYING: Wait for Online operator to install (10 retries left).
> FAILED - RETRYING: Wait for Online operator to install (9 retries left).
> FAILED - RETRYING: Wait for Online operator to install (8 retries left).
> FAILED - RETRYING: Wait for Online operator to install (7 retries left).
> ok: [localhost]
> 
> TASK [provision_online : Add the Security Constraint Context] *************************************************************************************************************************
> ok: [localhost]
> 
> TASK [provision_online : Set temp dir] ************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [provision_online : Ensure example directory exists] *****************************************************************************************************************************
> ok: [localhost]
> 
> TASK [provision_online : Download example files] **************************************************************************************************************************************
> skipping: [localhost]
> 
> TASK [provision_online : Create Online Plan Examples] *********************************************************************************************************************************
> ```
> 
> Maybe because the /tmp directory already contains the address plans, it skips the task maybe? Maybe we should consider removing the directory first if it already exists.

the only step that checks if the file exists is the unarchive one. 

It means that the file should be created from current files. What are the steps to reproduce?

**Comment by hguerrero** [comment]
Closing as this should be fixed now.
