### ISSUE TITLE
Module 3 premiumshipping-config.yaml is missing java.util.HashMap

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-streaming#66]
I need to correct line 19 of the YAML file to include java.util.HashMap to the whitelist:

```
infinispan.client.hotrod.java_serial_whitelist=java.util.ArrayList,java.util.LinkedHashMap,java.util.HashMap
```

Please update the template premiumshipping-config.yaml file to include this whitelist entry.

**Comment by weimeilin79** [comment]
Fix this this commit. https://github.com/RedHatWorkshops/dayinthelife-streaming/commit/a753fec8b56d68269c8d38dc975fdf9e533d7aee
