### ISSUE TITLE
Make International DB persistent

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/dayinthelife-streaming#7]
Currently the ms-sqlserver DB is ephemeral.  Whenever the OCP 4 cluster reboots, the International DB is lost.

**Comment by hguerrero** [comment]
yes, the db is ephemeral but the deployment is configured to initialize the database everytime the pod restarts. 

what happens is that you lose what ever you stored before, but the structure remains after the pod restart. 

do you want to keep the records? do we need it?

**Comment by hguerrero** [comment]
PR sent for implement this. This will also solve #33 

PR https://github.com/redhat-cop/agnosticd/pull/2331
